[FEATURE] Add T3kit10 php7.4 apache 2.4 buster docker files
t3kit/t3kit-dockerhub pull request #3
Opened 2020-03-31 08:44 UTC by pixelmatseriks

# New Pull Request checklist

## Please check if your PR fulfills the following requirements

- [x] Contributing to t3kit: <https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md>
- [x] Coding Rules: <https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules>
- [x] Commit message conventions: <https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#commit-message-guidelines>

## PR Type

What kind of change does this PR introduce?

- [x] [FEATURE] - A new feature
- [ ] [BUGFIX] - A bug fix
- [ ] [TASK] - Any task, which is not a **new feature** or **bugfix**
- [ ] [TEST] - Adding missing tests
- [ ] [DOC] - Documentation only changes
- [ ] [WIP] - Work in progress tag, should not be present when creating pull requests
- [ ] [SECURITY] - To mark important updates, when evaluating when we should update older sites

## Breaking change

Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Issue references

Issue Number: #...

## Description

2020-03-31 08:59 UTC, dmh requested changes
Can you also add hadolint check in code-guidelines.yml

2020-03-31 08:59 UTC, dmh commented on t3kit10/php7.4-apache2.4-buster/Dockerfile
> +# t3kit/10-php7.3-apache2.4-stretch
t3kit/10-php7.4-apache2.4-buster

2020-03-31 08:59 UTC, dmh commented on t3kit10/php7.4-apache2.4-buster/Dockerfile
> +    imagemagick=8:6.* \
we can skip imagemagick since Platform doesn't support this. What do you think?

2020-04-01 09:30 UTC, pixelmatseriks commented
> Can you also add hadolint check in code-guidelines.yml
the hadolint check is added in code-guidelines.yml

2020-04-01 14:37 UTC, dmh approved these changes

2020-04-01 14:37 UTC, merged